version: '3'
services:
  server1:
    image: server
    ports:
      - "3000:3000"
  server2:
    image: server
    ports:
      - "3001:3000"
  server3:
    image: server
    ports:
      - "3002:3000"